# Generated by Django 5.2.5 on 2025-09-12 22:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BienPatrimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_inventario', models.CharField(max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('tipo', models.CharField(choices=[('EQUIPO_MEDICO', 'Equipo Médico'), ('INFORMATICA', 'Equipo Informático'), ('MOBILIARIO', 'Mobiliario'), ('VEHICULO', 'Vehículo'), ('OTRO', 'Otro')], max_length=50)),
                ('marca', models.CharField(blank=True, max_length=100)),
                ('modelo', models.CharField(blank=True, max_length=100)),
                ('numero_serie', models.CharField(blank=True, max_length=100)),
                ('fecha_adquisicion', models.DateField()),
                ('valor_adquisicion', models.DecimalField(decimal_places=2, max_digits=12)),
                ('proveedor', models.CharField(blank=True, max_length=200)),
                ('ubicacion_actual', models.CharField(max_length=200)),
                ('responsable', models.CharField(max_length=200)),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo'), ('MANTENIMIENTO', 'En mantenimiento'), ('BAJA', 'Dado de baja')], default='ACTIVO', max_length=50)),
                ('observaciones', models.TextField(blank=True)),
                ('fecha_ultimo_mantenimiento', models.DateField(blank=True, null=True)),
                ('proximo_mantenimiento', models.DateField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('usuario_creacion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bien Patrimonial',
                'verbose_name_plural': 'Bienes Patrimoniales',
                'ordering': ['numero_inventario'],
            },
        ),
    ]
