# Generated by Django 5.2.5 on 2025-09-16 19:34

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_expediente'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bienpatrimonial',
            name='cuenta_codigo',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='bienpatrimonial',
            name='donante',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='bienpatrimonial',
            name='expediente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bienes', to='core.expediente'),
        ),
        migrations.AddField(
            model_name='bienpatrimonial',
            name='numero_identificacion',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Número de Identificación'),
        ),
        migrations.AddField(
            model_name='bienpatrimonial',
            name='origen',
            field=models.CharField(choices=[('DONACION', 'Donación'), ('OMISION', 'Omisión'), ('TRANSFERENCIA', 'Transferencia/Traslado'), ('COMPRA', 'Compra')], default='COMPRA', max_length=15),
        ),
        migrations.AlterField(
            model_name='bienpatrimonial',
            name='valor_adquisicion',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddIndex(
            model_name='bienpatrimonial',
            index=models.Index(fields=['numero_inventario'], name='core_bienpa_numero__07e73a_idx'),
        ),
        migrations.AddIndex(
            model_name='bienpatrimonial',
            index=models.Index(fields=['tipo'], name='core_bienpa_tipo_527187_idx'),
        ),
        migrations.AddIndex(
            model_name='bienpatrimonial',
            index=models.Index(fields=['estado'], name='core_bienpa_estado_d48784_idx'),
        ),
    ]
