# Generated by Django 5.2.6 on 2025-09-20 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_bienpatrimonial_cuenta_codigo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expediente',
            name='proveedor',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
